// src/pages/QuickFileSearch.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { getCurrentWindow } from "@tauri-apps/api/window";

interface FileResult {
  name: string;
  path: string;
  size: number;
  is_dir: boolean;
}

const query = ref("");
const results = ref<FileResult[]>([]);
const isSearching = ref(false);
const selectedIndex = ref(-1);
const isIndexing = ref(false);
const indexProgress = ref({ current: 0, total: 0, message: "" });
const inputRef = ref<HTMLInputElement | null>(null);
const listRef = ref<HTMLDivElement | null>(null);
let debounceTimer: ReturnType<typeof setTimeout> | null = null;
let resultsCache: FileResult[] = [];

const getFileIcon = (name: string, isDir: boolean): string => {
  if (isDir) return "D";
  const ext = name.split(".").pop()?.toLowerCase() || "";
  const iconMap: Record<string, string> = {
    pdf: "P", doc: "P", docx: "P", txt: "T",
    jpg: "I", jpeg: "I", png: "I", gif: "I",
    mp3: "A", wav: "A", mp4: "V", avi: "V",
    zip: "Z", rar: "Z", exe: "E", lnk: "L",
    html: "H", css: "C", js: "J", ts: "T", json: "J",
    rs: "R", go: "G", py: "P", java: "J",
    md: "M", sql: "S",
  };
  return iconMap[ext] || "F";
};

onMounted(() => {
  setTimeout(() => inputRef.value?.focus(), 50);
  invoke("get_index_status").then((status: any) => {
    if (status && status.indexed_count > 0) {
      // has index
    } else {
      isIndexing.value = true;
      invoke("build_file_index").catch(() => (isIndexing.value = false));
    }
  }).catch(() => {});

  let unlistens: (() => void)[] = [];
  listen<FileResult[]>("file-search://result", (event) => {
    resultsCache = [...resultsCache, ...event.payload];
    results.value = [...resultsCache];
  }).then((fn) => unlistens.push(fn));
  listen("file-search://done", () => {
    isSearching.value = false;
  }).then((fn) => unlistens.push(fn));
  listen<any>("file-index://status", (event) => {
    const { phase } = event.payload;
    if (phase === "done") { isIndexing.value = false; }
    else if (phase === "error") { isIndexing.value = false; }
  }).then((fn) => unlistens.push(fn));
  listen<any>("file-index://progress", (event) => {
    indexProgress.value = event.payload;
  }).then((fn) => unlistens.push(fn));

  onUnmounted(() => {
    unlistens.forEach((fn) => fn());
  });
});

const doSearch = async (q: string) => {
  const trimmed = q.trim();
  if (!trimmed) {
    results.value = [];
    resultsCache = [];
    isSearching.value = false;
    selectedIndex.value = -1;
    return;
  }
  isSearching.value = true;
  results.value = [];
  resultsCache = [];
  selectedIndex.value = -1;
  try { await invoke("search_files", { query: trimmed }); }
  catch (e) { console.error("Search failed:", e); isSearching.value = false; }
};

const handleInputChange = () => {
  if (debounceTimer) clearTimeout(debounceTimer);
  debounceTimer = setTimeout(() => doSearch(query.value), 80);
};

const openFile = async (file: FileResult) => {
  try {
    await invoke("open_file", { path: file.path });
    getCurrentWindow().close();
  } catch (e) { console.error("Open file failed:", e); }
};

const visibleResults = () => results.value.slice(0, 15);
</script>

<template>
  <div class="quick-search-container">
    <div class="quick-search-box">
      <div v-if="isIndexing" class="quick-index-bar">
        <span>
          {{ indexProgress.message || "Indexing..." }}
          <template v-if="indexProgress.total > 0">({{ indexProgress.current }} / {{ indexProgress.total }})</template>
        </span>
      </div>

      <div class="quick-input-wrapper">
        <input
          ref="inputRef"
          type="text"
          class="quick-input"
          placeholder="Search files..."
          v-model="query"
          @input="handleInputChange"
          @keydown.up.prevent="selectedIndex = Math.max(-1, selectedIndex - 1)"
          @keydown.down.prevent="selectedIndex = Math.min(visibleResults().length - 1, selectedIndex + 1)"
          @keydown.enter="selectedIndex >= 0 && openFile(visibleResults()[selectedIndex])"
          @keydown.escape="getCurrentWindow().close()"
        />
        <button v-if="query" class="quick-clear-btn" @click="query = ''; results = []; resultsCache = []; selectedIndex = -1; inputRef?.focus()">x</button>
      </div>

      <div class="quick-results" ref="listRef">
        <div v-if="isSearching && results.length === 0" class="quick-status">Searching...</div>
        <div v-else-if="!isSearching && query.trim() && results.length === 0" class="quick-status">No results</div>

        <div
          v-for="(file, index) in visibleResults()"
          :key="file.path"
          :class="['quick-result-item', { selected: index === selectedIndex }]"
          @click="openFile(file)"
          @mouseenter="selectedIndex = index"
        >
          <span class="quick-file-icon">{{ getFileIcon(file.name, file.is_dir) }}</span>
          <div class="quick-file-info">
            <div class="quick-file-name" :title="file.name">{{ file.name }}</div>
            <div class="quick-file-path" :title="file.path">{{ file.path }}</div>
          </div>
          <span v-if="index < 9" class="quick-shortcut-hint">Ctrl+{{ index + 1 }}</span>
        </div>

        <div v-if="results.length > 15" class="quick-more-hint">{{ results.length - 15 }} more results...</div>
      </div>

      <div class="quick-footer">
        <span class="quick-footer-hint">
          {{ isIndexing ? "Search will be faster after indexing" : results.length > 0 ? `${results.length} results` : isSearching ? "Searching..." : "Type to search" }}
        </span>
        <span class="quick-footer-keys">Up/Down Select Enter Open Esc Close</span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.quick-search-container { display: flex; flex-direction: column; height: 100vh; background: rgba(20,20,35,0.95); color: #e0e0e0; }
.quick-search-box { display: flex; flex-direction: column; height: 100%; }
.quick-index-bar { padding: 6px 12px; background: rgba(233,69,96,0.15); font-size: 11px; color: #e94560; }
.quick-input-wrapper { display: flex; align-items: center; padding: 8px 12px; border-bottom: 1px solid rgba(255,255,255,0.06); }
.quick-input { flex: 1; background: transparent; border: none; color: #e0e0e0; font-size: 14px; outline: none; }
.quick-clear-btn { background: none; border: none; color: rgba(255,255,255,0.3); cursor: pointer; font-size: 16px; }
.quick-results { flex: 1; overflow-y: auto; }
.quick-status { display: flex; align-items: center; justify-content: center; padding: 24px; color: rgba(255,255,255,0.4); font-size: 13px; }
.quick-result-item { display: flex; align-items: center; gap: 10px; padding: 8px 12px; cursor: pointer; transition: background 0.1s; }
.quick-result-item:hover,
.quick-result-item.selected { background: rgba(255,255,255,0.08); }
.quick-file-icon { width: 24px; text-align: center; font-size: 14px; flex-shrink: 0; }
.quick-file-info { flex: 1; min-width: 0; }
.quick-file-name { font-size: 13px; color: #e0e0e0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.quick-file-path { font-size: 10px; color: rgba(255,255,255,0.35); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.quick-shortcut-hint { font-size: 10px; color: rgba(255,255,255,0.25); flex-shrink: 0; }
.quick-more-hint { text-align: center; padding: 8px; font-size: 11px; color: rgba(255,255,255,0.3); }
.quick-footer { display: flex; justify-content: space-between; padding: 6px 12px; background: rgba(255,255,255,0.03); border-top: 1px solid rgba(255,255,255,0.06); font-size: 10px; color: rgba(255,255,255,0.3); }
</style>

// src/components/QuickFileSearch.tsx
import { useState, useRef, useEffect, useCallback, type ReactNode } from "react";
import { invoke } from "@tauri-apps/api/core";
import { listen, UnlistenFn } from "@tauri-apps/api/event";
import { getCurrentWindow } from "@tauri-apps/api/window";
import "./QuickFileSearch.css";

interface FileResult {
  name: string;
  path: string;
  size: number;
  is_dir: boolean;
}

function getFileIcon(name: string, isDir: boolean): string {
  if (isDir) return "📁";
  const ext = name.split(".").pop()?.toLowerCase() || "";
  const iconMap: Record<string, string> = {
    pdf: "📃", doc: "📃", docx: "📃", txt: "📃", rtf: "📃",
xls: "📈", xlsx: "📈", csv: "📈",
jpg: "📸", jpeg: "📸", png: "📸", gif: "📸", svg: "📸", webp: "📸", bmp: "📸", ico: "📸",
mp3: "🎧", wav: "🎧", flac: "🎧", ogg: "🎧",
mp4: "🎬", avi: "🎬", mkv: "🎬", mov: "🎬",
zip: "🗃️", rar: "🗃️", "7z": "🗃️", tar: "🗃️", gz: "🗃️",
exe: "🖥️", dll: "🖥️", msi: "💿", lnk: "🔗",
html: "🌐", htm: "🌐", css: "🎨", js: "📘", ts: "📘", jsx: "📘", tsx: "📘",
json: "🗂️", xml: "🗂️", yaml: "🗂️", yml: "🗂️",
rs: "🦀", go: "🐹", py: "🐍", java: "☕", cpp: "🔧", c: "🔧", h: "🔧", cs: "🔧",
sql: "💾", db: "💾",
md: "📓",
  };
  return iconMap[ext] || "📄";
}

// 判断是否为可提取图标的可执行文件类型
const EXECUTABLE_EXTS = new Set(["exe", "lnk", "msi"]);
function isExecutableFile(name: string, isDir: boolean): boolean {
  if (isDir) return false;
  const ext = name.split(".").pop()?.toLowerCase() || "";
  return EXECUTABLE_EXTS.has(ext);
}

// 可执行文件图标组件：异步加载真实图标，回退显示 emoji
function ExecutableIcon({ file }: { file: FileResult }) {
  const [iconSrc, setIconSrc] = useState<string | null>(null);
  const loadedRef = useRef(false);

  useEffect(() => {
    if (loadedRef.current) return;
    loadedRef.current = true;
    invoke<string | null>("get_file_icon", { filePath: file.path })
      .then((dataUri) => {
        if (dataUri) {
          setIconSrc(dataUri);
        }
      })
      .catch(() => {});
  }, [file.path]);

  const fallback = getFileIcon(file.name, file.is_dir);
  if (!iconSrc) {
    return <span className="quick-file-icon">{fallback}</span>;
  }
  return (
    <span className="quick-file-icon">
      <img src={iconSrc} alt="" className="quick-app-icon" />
    </span>
  );
}

function highlightMatch(text: string, query: string): ReactNode {
  if (!query) return <>{text}</>;
  const lowerText = text.toLowerCase();
  const lowerQuery = query.toLowerCase();
  const parts: ReactNode[] = [];
  let lastIndex = 0;

  // 找到所有匹配位置
  let searchFrom = 0;
  while (true) {
    const idx = lowerText.indexOf(lowerQuery, searchFrom);
    if (idx === -1) break;

    if (idx > lastIndex) {
      parts.push(<span key={`${lastIndex}-pre`}>{text.slice(lastIndex, idx)}</span>);
    }
    parts.push(
      <mark key={idx} className="quick-match-highlight">
        {text.slice(idx, idx + query.length)}
      </mark>
    );
    lastIndex = idx + query.length;
    searchFrom = idx + 1;
  }

  if (lastIndex < text.length) {
    parts.push(<span key={`${lastIndex}-post`}>{text.slice(lastIndex)}</span>);
  }

  return <>{parts}</>;
}

export default function QuickFileSearch() {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<FileResult[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [selectedIndex, setSelectedIndex] = useState(-1);
  const [useIndex, setUseIndex] = useState(false);
  const [isIndexing, setIsIndexing] = useState(false);
  const [indexProgress, setIndexProgress] = useState({ current: 0, total: 0, message: "" });
  const inputRef = useRef<HTMLInputElement>(null);
  const listRef = useRef<HTMLDivElement>(null);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const resultsRef = useRef<FileResult[]>([]);
  const hasAutoBuiltRef = useRef(false);

  // Auto focus on mount & check index status
  useEffect(() => {
    setTimeout(() => inputRef.current?.focus(), 50);

    // 检查索引状态，未建立则自动构建
    invoke("get_index_status").then((status: any) => {
      if (status && status.indexed_count > 0) {
        setUseIndex(true);
      } else if (!hasAutoBuiltRef.current) {
        hasAutoBuiltRef.current = true;
        setIsIndexing(true);
        invoke("build_file_index").catch(() => setIsIndexing(false));
      }
    }).catch(() => {});
  }, []);

  // Listen for file search results & index events
  useEffect(() => {
    let unlistenResult: UnlistenFn | undefined;
    let unlistenDone: UnlistenFn | undefined;
    let unlistenIndexStatus: UnlistenFn | undefined;
    let unlistenIndexProgress: UnlistenFn | undefined;

    const setupListeners = async () => {
      unlistenResult = await listen<FileResult[]>("file-search://result", (event) => {
        resultsRef.current = [...resultsRef.current, ...event.payload];
        setResults([...resultsRef.current]);
      });

      unlistenDone = await listen<string>("file-search://done", () => {
        setIsSearching(false);
      });

      unlistenIndexStatus = await listen<any>("file-index://status", (event) => {
        const { phase } = event.payload;
        if (phase === "building") {
          setIsIndexing(true);
        } else if (phase === "done") {
          setIsIndexing(false);
          setUseIndex(true);
          setIndexProgress({ current: 0, total: 0, message: "" });
        } else if (phase === "error") {
          setIsIndexing(false);
        }
      });

      unlistenIndexProgress = await listen<any>("file-index://progress", (event) => {
        const { current, total, message } = event.payload;
        setIndexProgress({ current, total, message });
      });
    };

    setupListeners();

    return () => {
      if (unlistenResult) unlistenResult();
      if (unlistenDone) unlistenDone();
      if (unlistenIndexStatus) unlistenIndexStatus();
      if (unlistenIndexProgress) unlistenIndexProgress();
    };
  }, []);

  const doSearch = useCallback(async (q: string) => {
    const trimmed = q.trim();
    if (!trimmed) {
      setResults([]);
      resultsRef.current = [];
      setIsSearching(false);
      setSelectedIndex(-1);
      return;
    }
    setIsSearching(true);
    setResults([]);
    resultsRef.current = [];
    setSelectedIndex(-1);
    try {
      await invoke("search_files", { query: trimmed });
    } catch (e) {
      console.error("搜索文件失败:", e);
      setIsSearching(false);
    }
  }, []);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value;
    setQuery(val);
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => doSearch(val), 80);
  };

  const openFile = async (file: FileResult) => {
    try {
      await invoke("open_file", { path: file.path });
      getCurrentWindow().close();
    } catch (e) {
      console.error("打开文件失败:", e);
    }
  };

  const revealInFolder = async (file: FileResult) => {
    try {
      await invoke("reveal_in_folder", { path: file.path });
      getCurrentWindow().close();
    } catch (e) {
      console.error("打开所在文件夹失败:", e);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    // Ctrl+1~9 快速打开
    if (e.ctrlKey && e.key >= "1" && e.key <= "9") {
      e.preventDefault();
      const idx = parseInt(e.key, 10) - 1;
      if (idx >= 0 && idx < results.length) {
        openFile(results[idx]);
      }
      return;
    }

    if (e.key === "ArrowDown") {
      e.preventDefault();
      setSelectedIndex((prev) => Math.min(prev + 1, results.length - 1));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setSelectedIndex((prev) => Math.max(prev - 1, -1));
    } else if (e.key === "Enter") {
      e.preventDefault();
      if (selectedIndex >= 0 && selectedIndex < results.length) {
        if (e.ctrlKey) {
          revealInFolder(results[selectedIndex]);
        } else {
          openFile(results[selectedIndex]);
        }
      }
    } else if (e.key === "Escape") {
      e.preventDefault();
      getCurrentWindow().close();
    }
  };

  // Auto-scroll to selected item
  useEffect(() => {
    if (selectedIndex >= 0 && listRef.current) {
      const items = listRef.current.querySelectorAll(".quick-result-item");
      if (items[selectedIndex]) {
        items[selectedIndex].scrollIntoView({ block: "nearest" });
      }
    }
  }, [selectedIndex]);

  const handleItemClick = (file: FileResult) => {
    openFile(file);
  };

  const handleItemContextMenu = (e: React.MouseEvent, file: FileResult) => {
    e.preventDefault();
    revealInFolder(file);
  };

  const clearSearch = () => {
    setQuery("");
    setResults([]);
    resultsRef.current = [];
    setIsSearching(false);
    setSelectedIndex(-1);
    inputRef.current?.focus();
  };

  const visibleResults = results.slice(0, 15);

  return (
    <div className="quick-search-container">
      <div className="quick-search-box">
        {/* 索引状态提示 */}
        {isIndexing && (
          <div className="quick-index-bar">
            <div className="quick-spinner-small" />
            <span>
              {indexProgress.message || "正在建立索引..."}
              {indexProgress.total > 0 && ` (${indexProgress.current} / ${indexProgress.total})`}
            </span>
          </div>
        )}
        {!useIndex && !isIndexing && (
          <div className="quick-index-bar quick-index-hint">
            <span>⚡ 首次使用，正在后台建立索引，请稍候...</span>
          </div>
        )}

        {/* 搜索输入区 */}
        <div className="quick-input-wrapper">
          <span className="quick-search-icon">🔍</span>
          <input
            ref={inputRef}
            type="text"
            className="quick-input"
            placeholder="搜索文件..."
            value={query}
            onChange={handleInputChange}
            onKeyDown={handleKeyDown}
          />
          {query && (
            <button className="quick-clear-btn" onClick={clearSearch} title="清除">
              ×
            </button>
          )}
        </div>

        {/* 结果列表 */}
        <div className="quick-results" ref={listRef}>
          {isSearching && results.length === 0 && (
            <div className="quick-status">
              <div className="quick-spinner" />
            </div>
          )}

          {!isSearching && query.trim() && results.length === 0 && (
            <div className="quick-status">
              <span>未找到匹配文件</span>
            </div>
          )}

          {visibleResults.map((file, index) => (
            <div
              key={`${file.path}-${index}`}
              className={`quick-result-item ${index === selectedIndex ? "selected" : ""}`}
              onClick={() => handleItemClick(file)}
              onContextMenu={(e) => handleItemContextMenu(e, file)}
              onMouseEnter={() => setSelectedIndex(index)}
            >
              {isExecutableFile(file.name, file.is_dir) ? (
                <ExecutableIcon file={file} />
              ) : (
                <span className="quick-file-icon">{getFileIcon(file.name, file.is_dir)}</span>
              )}
              <div className="quick-file-info">
                <div className="quick-file-name" title={file.name}>
                  {highlightMatch(file.name, query)}
                </div>
                <div className="quick-file-path" title={file.path}>
                  {file.path}
                </div>
              </div>
              {index < 9 && (
                <span className="quick-shortcut-hint">Ctrl+{index + 1}</span>
              )}
            </div>
          ))}

          {results.length > 15 && (
            <div className="quick-more-hint">
              还有 {results.length - 15} 个结果...
            </div>
          )}
        </div>

        {/* 底部提示 */}
        <div className="quick-footer">
          <span className="quick-footer-hint">
            {isIndexing
              ? "索引构建完成后搜索将秒级响应"
              : results.length > 0
              ? `共 ${results.length} 个结果`
              : isSearching
              ? "搜索中..."
              : "输入关键词开始搜索"}
          </span>
          <span className="quick-footer-keys">
            ↑↓ 选择 · Enter 打开 · Ctrl+Enter 打开文件夹 · Esc 关闭
          </span>
        </div>
      </div>
    </div>
  );
}
